baseURL = "/"
languageCode = "en"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2019 Stackacademy.tv"
disableKinds = ["section"]
DefaultContentLanguage = "en"
[outputs]
  home = ["HTML", "JSON"]
