backend:
    name: git-gateway
i18n:
    # Required and can be one of multiple_folders, multiple_files or single_file
    # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
    # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
    # single_file - persists a single file in `<folder>/<slug>.<extension>`
    structure: multiple_folders
    
    # Required - a list of locales to show in the editor UI
    locales: [en, de, fr]
    
    # Optional, defaults to the first item in locales.
    # The locale to be used for fields validation and as a baseline for the entry.
    default_locale: en

local_backend: true
media_folder: static/media
public_folder: /media
collections:
    -   name : "page"
        i18n: true
        label : "Page"
        folder : "content/"
        create : true
        slug : "{{slug}}"
        fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Author", name: "author", widget: "select", options : ["Shejoy","Cherian"] }
            - { label: "Date", name: "date", widget: "datetime" }